# Generated by Django 2.1.3 on 2018-12-08 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booked',
            old_name='room_id',
            new_name='room',
        ),
    ]
