# Generated by Django 2.1.7 on 2019-02-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20190218_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='booked_to',
            field=models.DateField(default=None),
        ),
    ]
