# Generated by Django 2.1.7 on 2019-02-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20190218_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='booked_to',
            field=models.DateField(),
        ),
    ]
