# Generated by Django 2.1.7 on 2019-02-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20190218_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='booked_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='booked_to',
            field=models.DateField(null=True),
        ),
    ]
