# Generated by Django 2.1.7 on 2019-02-18 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20190218_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='booked_from',
        ),
        migrations.RemoveField(
            model_name='room',
            name='booked_to',
        ),
    ]
