# Generated by Django 2.1.7 on 2019-02-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20190218_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='booked_from',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='booked_to',
            field=models.DateField(null=True),
        ),
    ]
