# Generated by Django 2.1.7 on 2019-02-18 21:58

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20190218_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='booked_from',
            field=models.DateField(null=True, validators=[booking.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='booked',
            name='booked_to',
            field=models.DateField(null=True, validators=[booking.models.validate_date]),
        ),
    ]
